### ISSUE TITLE
Inputs/Outputs with Enums instead StringHash

### ISSUE THREAD

**Issue by MonkeyFirst** [1vanK/Urho3DFlowGraph#3]
Суть в том что порты удобнее переделать на числа, а не на мапу с StringHash'ом
Для того чтобы юзать Enum'ы

```
class URHO3D_API TimerFlowNode : public FlowNode
{
	URHO3D_OBJECT(TimerFlowNode, FlowNode);

public:

	enum TimerInputPorts
	{
		IN_TIMER_PERIOD,
		IN_TIMER_MAX_TICKS,
		IN_TIMER_LAST
	};

	enum TimerOutputPorts
	{
		OUT_TIMER_EVENT,
		OUT_TIMER_LAST
	};


	TimerFlowNode(Context* context);
	void Update(float timeStep);

	// Был ли уже отправлен сигнал.
	bool sended_ = false;
};
```
В последствии они используются в конструкторе

```
TimerFlowNode::TimerFlowNode(Context * context)
{
	// Создаем входные порты.
	SharedPtr<FlowInputPort> periodInputPort(new FlowInputPort(context));
	periodInputPort->node_ = this;
	periodInputPort->data_ = Variant(1); // default value
	inputs_[IN_TIMER_PERIOD] = periodInputPort;

	SharedPtr<FlowInputPort> maxTicksInputPort(new FlowInputPort(context));
	maxTicksInputPort->node_ = this;
	maxTicksInputPort->data_ = Variant(10); // default value
	inputs_[IN_TIMER_MAX_TICKS] = maxTicksInputPort;
```

**Comment by 1vanK** [comment]
Можно для строк константы делать в коде, но из кода их юзать бессмысленно, так что нет разницы какие идентификаторы. А вот разве в редакторе не удобно будет, когда порты имеют имена?

**Comment by MonkeyFirst** [comment]
map'a vs vector :) + enum удобнее все группировано в выпадающем списке
И потом смотри как компактно может это выглядеть
```
	// Create flownode
	CGameEntityNodeFactory &nodeFactory = CGameFactory::RegisterEntityFlowNode("Character");

	// Define input ports, and the callback function for when they are triggered
	std::vector<SInputPortConfig> inputs;
	inputs.push_back(InputPortConfig_Void("TurnOn", "Turns the Area on"));
	inputs.push_back(InputPortConfig_Void("TurnOff", "Turns the Area off"));
	inputs.push_back(InputPortConfig_Void("GetStates", "Query Character states into outputs"));
	inputs.push_back(InputPortConfig_Void("TryToFindPlayer", "Query Character for going closer to the Player"));

	nodeFactory.AddInputs(inputs, OnFlowgraphActivation);

	std::vector<SOutputPortConfig> outputs;
	outputs.push_back(OutputPortConfig_Void("IsMove", "If character moves"));
	outputs.push_back(OutputPortConfig<float>("Speed", "Character speed"));
	outputs.push_back(OutputPortConfig<int>("EntityId", "Character Entity id"));
	outputs.push_back(OutputPortConfig<Vec3>("Direction", "Move Direction"));
	outputs.push_back(OutputPortConfig<bool>("IsGrounded", "Character on ground"));
	//outputs.push_back(OutputPortConfig_AnyType("IsActive", "If player leave area"));
	nodeFactory.AddOutputs(outputs);
```
А вот где юзаются enum'ы, для обработки входящих сигналов
```
void CCharacter::OnFlowgraphActivation(EntityId entityId, IFlowNode::SActivationInfo *pActInfo, const class CFlowGameEntityNode *pNode)
{
	if (auto *pCharacter = static_cast<CCharacter *>(QueryExtension(entityId)))
	{
		if (IsPortActive(pActInfo, eInputPort_TurnOn))
		{
			pCharacter->GetEntity()->Hide(false);

		}
		else if (IsPortActive(pActInfo, eInputPort_TurnOff))
		{
			pCharacter->GetEntity()->Hide(true);
		}
		else if (IsPortActive(pActInfo, eInputPort_GetState))
		{
			pCharacter->OutputAllFG();
		}
		else if (IsPortActive(pActInfo, eInputPort_TryToFindPlayer))
		{
			pCharacter->FGAction_TryToFindPlayer();
		}

	}
}
```

**Comment by MonkeyFirst** [comment]
>А вот разве в редакторе не удобно будет, когда порты имеют имена?

Я пока не думал, на это счет, но да удобнее будет опросить FlowNode->GetNumInputs() и перебрать ей порты FlowNode->GetInputPort(int index) для выходящих портов равнозначная ситуция.

**Comment by Zamir7** [comment]
Пожалуйста, откажитесь от практики отдельных контролов - не плодите эти классы как грибов после дождя( 

Давайте продумаем универсальный контрол...

**Comment by Zamir7** [comment]
просто у них много общего, а тот минимум расхождений прилепим... да хоть пластилином, на первых порах

**Comment by Zamir7** [comment]
TimerFlowNode, CameraControllerFlowNode вы не успеете оглянуться как им счет потеряете

**Comment by MonkeyFirst** [comment]
Да их где-то 100-200+ стандартных должно быть на все случаи жизни + кастомных сколько хочешь ))
Ты загляни в CryEngine или в UE4 там их просто море...
В этом весь смысл кирпичей, нельзя изобрести один универсальный. 
Каждый кирпич делает какое-то стандартное для него - "движение в движке"
один текстуры подгружает для смены на меше, другой вектора считает, третий триггер и посылает сигналы...

У меня на таймереФлоуНоде почти обратный счет работает )

**Comment by Zamir7** [comment]
> , нельзя изобрести один универсальный.

а ты уже думал об этом?) или нутро подсказывает))

**Comment by 1vanK** [comment]
По моей задумке UI элементы для флоунод будут создаваться на лету в редакторе

**Comment by Zamir7** [comment]
Вот грубый план: все "умения" ваших кирпичиков, кидаем в отдельный класс - красиво и понятно разграниченные, а в другом храним все enumЫ - для каждого кирпичика, как инфу - что и как тянуть с первого класса...

**Comment by 1vanK** [comment]
Zamir7

есть один базовый класс для флоуноды, который ничего не делает, и его нужно наполнить функционалом. Что ты понимаешь под универсальным контролом? Мне кажется ты вообще про UI элементы говоришь. UI элементы создавать не надо будет, они будут генерироваться на лету для флоунод в зависимости от числа выходных выходных портов и их типа

**Comment by Zamir7** [comment]
> Мне кажется ты вообще про UI 

отнюдь

**Comment by MonkeyFirst** [comment]
>По моей задумке UI элементы для флоунод будут создаваться на лету в редакторе
Да вполне можно на лету собирать UI для флоу ноды, только я не понял а SetMovable() имеет лишь Window? его можно юзать для флоунод в графе ? Или есть что попроще "перемещаемое" ?

**Comment by 1vanK** [comment]
но что значит весь функционал? один блок может получать нажатия клавишь, а другой писать в файл.  а третий должен генерировать случайные числа, а пете с москвы может понадобиться чтобы блок пускал феерверки. как это можно в один класс запихать? это все равно что сорать все классы движка и запихать в один файл

**Comment by Zamir7** [comment]
>  SetMovable() имеет лишь Window 

помоему и uielement тоже

**Comment by 1vanK** [comment]
> Или есть что попроще "перемещаемое" ?

это и так простой класс, картинка которую можно перемещать мышкой))

**Comment by Zamir7** [comment]
но что значит весь функционал? это все что умеет движок, правильно ты заметил, но разложенные по полочкам в одном классе... со второго "инфо" класса, где уже есть конкретизация элементов - мы дергаем именно те функции что ему нужны. Хочешь на основе создавай на лету код элемента, хочешь тяни монстра каждый раз.

**Comment by Zamir7** [comment]
И подобно игре Spore - можно будет легко создавать диковенные пользовательские  элементы

**Comment by 1vanK** [comment]
MonkeyFirst

кстати я вот думаю входные порты не обязательно сбоку рисовать, вот например входной порт типа цвет, можно на UI Элементе цветовой круг рисовать, короч как в блендере, тут вообще полет фантазии

![2](https://cloud.githubusercontent.com/assets/13021826/21295670/42be9618-c56b-11e6-975a-98133500f9d3.png)

**Comment by Zamir7** [comment]
Я же не противлюсь, что мысль сырая, но лишать ее жизни по этой причине...может не будем торопиться(

**Comment by Zamir7** [comment]
>  не обязательно сбоку рисовать

как и переменные

**Comment by MonkeyFirst** [comment]
>UI Элементе цветовой круг рисовать, короч как в блендере, тут вообще полет фантазии
у нее один выход, по сути это нода-параметр с визуальной подстройкой

**Comment by MonkeyFirst** [comment]
она на страте графа должна один раз выполнятся чтобы записать себе на вход цвет или даже той след. ноде.

**Comment by 1vanK** [comment]
просто я другого примера не нашел, то есть вот допустим нода, у нее цвет может как извне поступить, а если нет входящего соединения, то юзер цвет настраивает, вот для настройки цвета пользователем прям на контроле цветовой круг, ну и разъем оставить конечно для входящего подключения (хз может даже прятать цветовой круг, если есть подключение)

**Comment by 1vanK** [comment]
то есть я имею в виду, что не просто точки для подключения, а более такие навороченные ноды
конечно на первых порах сделаем по простому - щелкаешь по точке - открывается окошко для ввода значения

**Comment by Zamir7** [comment]
продолжая тему) вот к примеру тот же самый цветовой круг, состоим из маленьких умений и ф-ий, как то movable кружок, слайдер, color, ф-ия загрузки карты цветов и т.д. Вот их я и имел в виду, и они не должны нигде повторяться - т.к вы задумали в кубиках.

**Comment by MonkeyFirst** [comment]
естественно в начале - чем проще тем лучше)
еще не понятно насколько быстро это все будет работать, а так же со сложными связями между нодами непроверена работа графа

**Comment by 1vanK** [comment]
вот допустим 300 нод в графе это офигеть как много, типично сколько нод? ну 20 30, если очень сложная,

но даже если принять 300 нод, то даже при самом плохом раскладе, все ноды будут выполненны за 300 проходов цикла (то есть когда неапдейченая нода будет найдена в самом конце), опять же оптимизации потом можно сделать со всякими сортировками нод перед выполненим

**Comment by 1vanK** [comment]
а сами ноды между собой очень быстро общаются, там передача данных через указатели

**Comment by MonkeyFirst** [comment]
параметрическая нода (число/вектор/имя файла) это типа Starter'a один раз отправляет и все ?

> и они не должны нигде повторяться

а где он будет повторятся?
у нее есть класс ColorSelectorFlowNode и ее визуальное предствление в редакторе.
инстансов ColorSelectorFlowNode может быть много с разными значениями в графе, но класс написан один раз, его UI написано тоже 1 раз

**Comment by Zamir7** [comment]
> но даже если принять 300 нод

для компа это мелочь, вы что серьезно

**Comment by Zamir7** [comment]
> его UI написано тоже 1 раз

но его Ui состоит из многих составляющих, которые в свою очередь будут в составе еще многих кубиков

**Comment by Zamir7** [comment]
в общем, я предлагаю для формирования кубиков, создать фабрику кубиков (из атомарных элементов) - а не китайскую ручную работу

**Comment by 1vanK** [comment]
> параметрическая нода (число/вектор/имя файла) это типа Starter'a один раз отправляет и все ?

ты немного не так понимаешь процесс, там нет никакой отправки
1) у каждой ноды есть входные порты, есть выходные порты и есть функция апдейт, которая вызывается каждый кадр
2) на входе может быть либо заданное пользователем значение какого-то типа, либо полученно от входящей ноды
3) функция апдейт берет входящее значение (ей пофигу каков источник  - пользователь или другая нода) что-то делает и пишет результат своей работы в выходящие порты

и эта вся логика работы каждой конкретной ноды

то есть параметрическая нода в своем апдейте просто пишет в выходящий порт какое-то значение

С моей точки зрения создание параметрических нод, которые просто выдают какое-то постоянно значение вообще сомнительно. Зачем они нужны. Не проще ли просто в ноде, куда ты хочешь отправить это значение, на входящем порте указать это значение.

**Comment by Zamir7** [comment]
Кто нибудь понимает что пишу?(

**Comment by 1vanK** [comment]
Я лично нет) моя мысль остановилась на момент, когда ты предложил весь функционал движка запихать в один класс)

**Comment by 1vanK** [comment]
вообще тебе надо картинку нарисовать , квадаратик, изображаюший ноду, и все все все входные и выходные порты для твоего универсального контрола, который делает все все все)

**Comment by Zamir7** [comment]
> весь функционал движка запихать в один класс)

с вашими кубиками вы этот весь функционал запихаете и не раз, помяните мое слово))

**Comment by MonkeyFirst** [comment]
>  помяните мое слово))
Ты покажи пример кодом на С++ другого я думаю мы не поймем )

**Comment by Zamir7** [comment]
> вообще тебе надо картинку нарисовать , квадаратик, изображаюший ноду, и все все все входные

ок, так будет проще...

**Comment by MonkeyFirst** [comment]
мне кажется это как-то нужно упростить

```
	// Создаем входные порты.
	SharedPtr<FlowInputPort> periodInputPort(new FlowInputPort(context));
	periodInputPort->node_ = this;
	periodInputPort->data_ = Variant(1.0f); // default value
	inputs_[InputPortsPeriod] = periodInputPort;

	SharedPtr<FlowInputPort> maxTicksInputPort(new FlowInputPort(context));
	maxTicksInputPort->node_ = this;
	maxTicksInputPort->data_ = Variant(5); // default value
	inputs_[InputPortsMaxTicks] = maxTicksInputPort;

	SharedPtr<FlowOutputPort> timerEventInputPort(new FlowOutputPort(context));
	timerEventInputPort->node_ = this;
	outputs_[OutputPortsTimerEvent] = timerEventInputPort;
```

**Comment by 1vanK** [comment]
Да, создам функции, AddPort(тип), задно контроль типов будет

**Comment by MonkeyFirst** [comment]
потомучто это только три порта и тонна текста )

**Comment by MonkeyFirst** [comment]
ты не забудь что порту нужно хранить нормальное название для UI а не стрингхеш
описание порта description
мб даже строки для UI helperoв типа - _HELP("vmin=0, vmax=1")

**Comment by 1vanK** [comment]
О, я даж не обатил внимание, что у меня хеши вместо строк, я это откуда-то с движка скопировал))

**Comment by MonkeyFirst** [comment]
Короче я протестил  свой таймер он создает 5 коробок с помошью cubeCreator, это - вин!)

**Comment by MonkeyFirst** [comment]
У меня уже ручки чешутся оверрайдить анимацияю какую-нибудь по-событию CollisionNodeEvent

**Comment by 1vanK** [comment]
Там вообще дофига еще пчего переделывать, классы на Serializable переделать и реализовать загрузку/сохранение, да и регистрировать ноды походу придется, чтобы сериализация работала

**Comment by 1vanK** [comment]
А если регистрировать ноды, то как к ним из редактора обращаться? Если этих нод в самом движке не будет?

**Comment by 1vanK** [comment]
Типа кастомный плеер надо делать со своими нодами и через него редактор запускать

**Comment by 1vanK** [comment]
Или вообще на редактор забить, а функционал редактирования нод прямо в игру добавить? )) Какую-то подсистему написать, чтобы открывался холст ну типа консоли но только холст)

**Comment by MonkeyFirst** [comment]
Ну все-таки в двиг придется инжектить это, (даже по персональному желанию, копируя куда-то файлы) но редактор все равно отдельный от того, чисто для кирпичей. я так думаю.

**Comment by 1vanK** [comment]
Вообще редактор внутриигровой - это то, о чем там на форуме страдают, можно начать с нод)

**Comment by MonkeyFirst** [comment]
от стандартног редактора нужно возможноть навешать на ноду FlowGraphComponent + указаь фал графа. В движеке должна по идее крутиться подсистема которая при загрузке подхватит эти графы и будет выполнять

**Comment by 1vanK** [comment]
Ну если стандартные ноды добавить в движок то нет проблем. Но допустим ты написал свою кастомную ноду (на c++)

**Comment by MonkeyFirst** [comment]
нет, внутриигровой редактор - хрень полная, редакторы - отдельно и игры - отдельно, как мухи и котлеты )

**Comment by 1vanK** [comment]
ну ладно это пофигу в принципе,  не всякий будет кастомные ноды писать, а если е му понадобится, то он их и в урхоплеер сможет добавить, чтоб они из редактора были доступны

**Comment by MonkeyFirst** [comment]
> Но допустим ты написал свою кастомную ноду (на c++)
дык редактор когда будет строить флоу граф он общается чисто с интерфейсным вариантом flownode перебирает ее порты и строит её представление на холсте. Я думаю ситуация должна выглядеть ровно так же как и с кастомной логикой LogicComponent. В проекте она доступна движку она не нужна.

**Comment by 1vanK** [comment]
В приципе верно, но тогда не будет возможности в редакторе запустить потестировать

**Comment by MonkeyFirst** [comment]
Мне например это и не надо) есть для этого собранный проект, а из за того что ты пересобрал логику в графе пересобирать проект не нужно

**Comment by 1vanK** [comment]
Хотя вот порты например в конструкторе ноды создаются, получится голая интерфейсная нода без портов

**Comment by MonkeyFirst** [comment]
почему голая?
case SerializeType::TimerFlowNode:
FlowNode* flownode = (FlowNode*) new TimerFlowNode();
case SerializeType::CubeCreator:
FlowNode* flownode = (FlowNode*) new CubeCreatorFlowNode();

нее ?

**Comment by 1vanK** [comment]
а в движке таких классов нет) TimerFlowNode и CubeCreatorFlowNode, это же кастомные ноды они только в игре)

**Comment by Zamir7** [comment]
Как интересно наблюдать, что вы сами приходите к тому о чем я говорил)

**Comment by 1vanK** [comment]
мы говорим о кастомных нодах, как это относится к твоему предложению? )

**Comment by Zamir7** [comment]
> мы говорим о кастомных нодах

а кроме них у вас разве еще что то будет?) Я вижу их - армию порочных, не имеющие ничего общего др. с другом, отчужденные и дорогие в производстве истуканы -  и не дай Бог, в движке поменяется Position на Pos или Vector3 на Vec3)

**Comment by 1vanK** [comment]
кастомные ноды - это те которые не в движке, которые юзер добавляют прямо в исходник своей игры, с нодами, которые в движе никаких проблем нет

**Comment by MonkeyFirst** [comment]
>а в движке таких классов нет)

точно) и редактор должен иметь как-то все новые флоуноды в наличии... хмм
ну честно говоря для флоу графа важно знать лишь параметры флоунод, типы портов, что с чем соединено, а не как они функционитуют, функциал проверятся при запуске проекта (не редактора Ухи).
а я думаю из сериализованного файла как-то можно вытащить инфу о типе инстанса ноды из флоуграфа и в проекте заистансить нужный.
 
> чем я говорил)

а ты разве не код на С++ должен был показать?)

>и не дай Бог, в движке поменяется Position на Pos или Vector3 на Vec3)

Crtl+H же

**Comment by 1vanK** [comment]
> а я думаю из сериализованного файла как-то можно вытащить инфу о типе инстанса ноды из флоуграфа и в проекте заистансить нужный.

и как он будет знать из какого файла доставать инфу?

**Comment by 1vanK** [comment]
а хотя да, можно

**Comment by MonkeyFirst** [comment]
Кстати последний твой коммит лучще бы продублировал имя чем менять хеши на строки )

**Comment by 1vanK** [comment]
почему?

**Comment by MonkeyFirst** [comment]
медленее же, нее?

**Comment by 1vanK** [comment]
А строки хранить во втором массиве?

**Comment by MonkeyFirst** [comment]
вообще 
PODVector<SharedPtr<FlowInputPort>> inputs_ 
PODVector<String> inputsNames_ (или имя хранить внутри FlowInputPort)
...
+ enums для индексации
имхо лучше

**Comment by 1vanK** [comment]
а где список портов? )

**Comment by MonkeyFirst** [comment]
Гит съел )

**Comment by MonkeyFirst** [comment]
не ну еще outputs_ же

**Comment by 1vanK** [comment]
не, я не пойму как ты хочешь сопоставить хэш с портом, там или еще один PODVector с портами или гит у тебя еще HachMap на PODVector заменил)

**Comment by 1vanK** [comment]
Ага, понял

**Comment by MonkeyFirst** [comment]
))
нет, зачем там вообще мапа на хешах или темболее на строках когда это просто массив

**Comment by MonkeyFirst** [comment]
порты все равно в конструкторе кастомной ноды задаются, что мешает определять для них еще enum'ы в заголовке кастомного класса, два разных enum'a один для входов другой для выходов

**Comment by 1vanK** [comment]
Ну в принципе наверное так и надо сделать, имя порта хранит в порте.

**Comment by 1vanK** [comment]
Я просто представляю гигантское количество enum'ов по 5 шутк на каждую ноду. Или сделать для них отдельный namespace как это сделано для событий?

**Comment by 1vanK** [comment]
Хотя не, один enum на ноду же?

**Comment by 1vanK** [comment]
Нет два входные и выходные

**Comment by MonkeyFirst** [comment]
Кстати видел такой регистратор ?

```
struct IEntityRegistrator
{
	IEntityRegistrator()
	{
		if (g_pFirst == nullptr)
		{
			g_pFirst = this;
			g_pLast = this;
		}
		else
		{
			g_pLast->m_pNext = this;
			g_pLast = g_pLast->m_pNext;
		}
	}

	virtual void Register() = 0;
	virtual void Unregister() = 0;

public:
	IEntityRegistrator *m_pNext;

	static IEntityRegistrator *g_pFirst;
	static IEntityRegistrator *g_pLast;
};
```
Он как-то по цепочке по всем наследникам проходится и регестрирует их.
Такой же финт можно для не-кастомных flownode проделать.

**Comment by MonkeyFirst** [comment]
пример найду простой...

**Comment by 1vanK** [comment]
Да лучше пример, я по исходнику понял, что какой-то связный список создается и все

**Comment by MonkeyFirst** [comment]
```
class CMyEntityRegistrator : public IEntityRegistrator
{
	virtual void Register() override
	{
  
	}

	virtual void Unregister() override
	{
	
	}

};

CMyEntityRegistrator g_myEntityRegistrator;
```
этот класс чисто для регистрации своих Entity в движке

**Comment by 1vanK** [comment]
в урхо же есть регистратор объектов уже

**Comment by MonkeyFirst** [comment]
да, но связного списка нет) чтобы один заголовок за другим сам регался

**Comment by 1vanK** [comment]
а как это поможет? у нас класс все равно не доступен в движке)

**Comment by MonkeyFirst** [comment]
да это и не должно было помочь с доступом, просто удобная связка саморегистрируищихся классов

**Comment by 1vanK** [comment]
а откуда список берется? и не проще в том месте где список есть просто цикл запустить для регистрации всего

**Comment by MonkeyFirst** [comment]
> а откуда список берется?

глобальные статические переменные ниже обьявляются сразу под регистратором.

Кстати вот кастомная нода регится, 
я уже кажется это выкладывал...

```
		// Register flow node
		// Factory will be destroyed by flowsystem during shutdown
		CEntityFlowNodeFactory* pFlowNodeFactory = new CEntityFlowNodeFactory("entity:MyEntity");

		pFlowNodeFactory->m_inputs.push_back(InputPortConfig<bool>("Hide", ""));
		pFlowNodeFactory->m_inputs.push_back(InputPortConfig<bool>("UnHide", ""));
		pFlowNodeFactory->m_inputs.push_back(InputPortConfig<string>("LoadGeometry", ""));
		pFlowNodeFactory->m_activateCallback = CMyEntity::OnFlowgraphActivation;

		pFlowNodeFactory->m_outputs.push_back(OutputPortConfig_Void("OnHide"));
		pFlowNodeFactory->m_outputs.push_back(OutputPortConfig_Void("OnUnHide"));


		pFlowNodeFactory->Close();
```

будет другая Entity или сотня других, но будет юзаться тоже самый класс CEntityFlowNodeFactory

**Comment by MonkeyFirst** [comment]
для обработки входящих иветнов/сигналов есть статически метод в Entity
static void OnFlowgraphActivation(EntityId entityId, IFlowNode::SActivationInfo* pActInfo, const class CEntityFlowNode* pNode);

**Comment by 1vanK** [comment]
я чет туплю, поздно уже, не понимаю нифига)

вот у нас есть класс

чтобы класс можно было сериализовать/десеривализовать нужно его зарегистрировать.
при регистрации создается грубо говоря таблица "имя типа в виде строки" -> тип, потому что у нас в файлах имена типов в виде строк.
То есть на старте движка мы регистрируем все наши ноды и только после этого мы можем загружать их из файлов.

И я делаю на старте игры 
Register(тип1);
Register(тип2);
Register(тип3);

А вот с тем кодом, что ты показал как будет происходить?

**Comment by Zamir7** [comment]
> Я просто представляю гигантское количество enum'ов по 5 шутк на каждую ноду. Или сделать для них отдельный namespace как это сделано для событий?

тепло

**Comment by MonkeyFirst** [comment]
там тоже самое, Register же статический у componentoв
```

class CPlayerRegistrator
	: public IEntityRegistrator
	, public CPlayer::SExternalCVars
{
	virtual void Register() override
	{
		CGamePlugin::RegisterEntityWithDefaultComponent<CPlayer>("Player");

		CGamePlugin::RegisterEntityComponent<CPlayerMovement>("PlayerMovement");
		CGamePlugin::RegisterEntityComponent<CPlayerInput>("PlayerInput");
		CGamePlugin::RegisterEntityComponent<CPlayerView>("PlayerView");
		CGamePlugin::RegisterEntityComponent<CPlayerAnimations>("PlayerAnimations");
		
		RegisterCVars();
	}
```
RegisterEntityComponent -static метод

**Comment by 1vanK** [comment]
А, понял ты вообще про другое) Я думал про регистрацию ноды как типа, а у тебя порты в ноду добавляются в примере

**Comment by 1vanK** [comment]
Ну так изи, раз порты на массив переделываются, то они также через push будут добавляться с указанием типа и имени

**Comment by MonkeyFirst** [comment]
>по 5 шутк на каждую ноду
это же все персонально для каждой ноды, 

пример опять же...
```
class CFlowNode_MyName : public CFlowBaseNode<eNCT_Instanced>
{
	//CRY_ENTITY_COMPONENT_CLASS(CMyEntity, IEntityComponent, "MyEntity", 0x3069A67BC64E4BE1, 0x934696AAAD38A0D3);
	//CRY_ENTITY_COMPONENT_CLASS(CFlowNode_MyName, "MyFlowNode", 0x3069A67B464E4BE1, 0x933696AAAD38A0D3);
public:
	enum EInputPorts
	{
		eInputPort_SomeInput0 = 0,
		eInputPort_SomeInput1,
		eInputPort_SomeInput2,
		eInputPort_Num
	};

	enum EOutputPorts
	{
		eOutputPorts_Alertness = 0,
		eOutputPorts_Num
	};
public:
	CFlowNode_MyName(SActivationInfo* pActInfo);

	virtual IFlowNodePtr Clone(SActivationInfo *pActInfo) override;
	virtual void GetMemoryUsage(ICrySizer* s) const override;
	virtual void GetConfiguration(SFlowNodeConfig& config) override;
	virtual void ProcessEvent(EFlowEvent event, SActivationInfo* pActInfo) override;
};

REGISTER_FLOW_NODE("entity:MyFlowNode", CFlowNode_MyName);
```

**Comment by 1vanK** [comment]
да кстати, enum в класс прятать и namespace не нужно, слушай, мы так крайэнжин скопируем)

**Comment by MonkeyFirst** [comment]
ну я же показывал тебе два пути с гитхаба где все это лежит в папках мб копируть?) вдруг заведется под ухой как есть )

**Comment by 1vanK** [comment]
не, сначала свой вариант надо делать, вдруг я удачнее придумаю) у крайтековцев же груз обратной совместимости, мб они бы хотели переделать, но не могут)

**Comment by Zamir7** [comment]
Со своими его недостатками)

**Comment by 1vanK** [comment]
это не недостатки, это изюминка))

**Comment by Zamir7** [comment]
Я про "мы так крайэнжин скопируем)")

**Comment by MonkeyFirst** [comment]
да надо конечно свой ) но, надо знать хотябы куда двигатся

**Comment by Zamir7** [comment]
Что может быть хуже подобием чего то?;)

**Comment by 1vanK** [comment]
в конце концов нас еще и засудить могут за копирование)) но в любом случае у меня используется состояния, а не сигналы и события)

**Comment by MonkeyFirst** [comment]
в коде "пока" еще нет ни строчки из краенджина, какой суд ?)

**Comment by 1vanK** [comment]
пока что нет, но ты кидай сюда куски кода, а я буду их в проект вставлять))))

**Comment by Zamir7** [comment]
Утро вечера мудренее) вы со своими "аж нетерпиться замутить" дойдете до точки невозврата , где все будет разбросано по полу и никому не будет дело до порядка, тем более перестраивания)

**Comment by MonkeyFirst** [comment]
>"аж нетерпиться замутить" 
а ты покажешь свой канонический вариант как все должно быть на самом деле ?) "суперфлоунод"

**Comment by 1vanK** [comment]
потерпи, ты думаешь это быстро нарисовать ноду с 5000 портов )

**Comment by Zamir7** [comment]
Завтра)

**Comment by MonkeyFirst** [comment]
да хотябы с 500...50... 5-ю главное понять принцип работы )

**Comment by Zamir7** [comment]
"суперфлоунод" название уже ты придумал - осталось за малым))

**Comment by 1vanK** [comment]
переделал на енумы
