### ISSUE TITLE
enum в AS

### ISSUE THREAD

**Issue by 1vanK** [1vanK/Urho3DFlowGraph#6]
Короче такая проблема, в C++ я могу enum входных и выходных портов запрятать в класс,
а в AS хз как. Пока сделал это в глобальной области видимости. Но понятное дело, что если каждая нода будет в глобальном пространстве именов создавать к примеру "IN_COLOR", это никуда не годится. Так что возможно придется вернуться с enumов на строковые названия портов, если не будет найдено решение.

**Comment by Zamir7** [comment]
Одобрямс

**Comment by 1vanK** [comment]
там уже есть инфа о типе, только не проверяется пока

**Comment by 1vanK** [comment]
+ возможен любой тип

**Comment by Zamir7** [comment]
инфа о типе - я имел в виду тип инпута и тип оутпута, чтобы при связывании, чел не мог не в ту дыру всунуть. Хотя, это можно же проверять на лету...

**Comment by Zamir7** [comment]
Иван, (тебя так же зовут?) А для с++ накладно рефлексировать методы и свойства объекта? Почему бы не работать с этим списком?

**Comment by 1vanK** [comment]
можно подробнее?

**Comment by Zamir7** [comment]
На входе получаешь лишь объект, а программно выдергиваешь все свойства (и методы?) объекта, юзеру предлагаешь выбрать нужную(ые) - в виде инпута или оутпута

**Comment by 1vanK** [comment]
Типа имеется в виду, что как в C# получать весь список членов? В C++ такого нет, потому что там нет runtime среды исполнения, поэтому делаются всякие навороты типи дефайна urho3d_object()

**Comment by Zamir7** [comment]
Да. Переходи на шарп!)

**Comment by Zamir7** [comment]
Может на AS есть?

**Comment by Zamir7** [comment]
> получать весь список членов?

ну ты объял их значимость , в данном контексте?) Хотя бы мысленно...

**Comment by Zamir7** [comment]
Да, список может быть громоздким, согласен, но можно разделить на группы - на самом вверху самые необходимые свойства (часто используемые), а под спойлером остальные, вдруг если потребуются. Но сколько свободы это даст!

**Comment by 1vanK** [comment]
в AS биндингах ниче само не появится, пока ты ручками на C++ не экспортнешь туда член класса

**Comment by 1vanK** [comment]
а есть же еще LUA и туда тоже придется экспортировать

**Comment by 1vanK** [comment]
так что от навороченных конструкций надо отказаться

**Comment by Zamir7** [comment]
Как вы выживаете в мире ++? XD

**Comment by Zamir7** [comment]
> Сейчас комитет по стандартизации С++ рассматривает предложения N4111, которое призывает расширить возможности рефлексии на этапе компиляции уже в следующем обновлении языка (С++17). А до той поры с решением нашей задачи на С++ лучше повременить.

**Comment by MonkeyFirst** [comment]
> Так что возможно придется вернуться с enumов на строковые названия портов, если не будет найдено решение.
(( не знаю даже что и сказать... какой же этот - AS... редиска!) 

>а есть же еще LUA и туда тоже придется экспортировать

О, нет еще же луа есть (( кому она нахр%н нужна ? ты ёю пользуешся ? мб забить на нее ?

>Куда CodingMonkey интересно делся, второй день его нет...

нашел интерсную стрелялку, не могу оторваться )

>Да. Переходи на шарп!)

Не, давай лучше ты на cpp :)

**Comment by 1vanK** [comment]
Zamir, Если ты еще раз про C# напишешь, я тебя придушу, отвечаю))
1) движок не на C# написан, а на си++, на C# там биндинги только, если не будет написано на C++ то и на C# не будет
2) Биндинги на C# тоже неподъемная задача для меня, как я писал раньше

**Comment by 1vanK** [comment]
MonkeyFirst я бы и на anglescript забил, но тогда флоу в движке не будет)

**Comment by Zamir7** [comment]
>  Если ты еще раз про C# напишешь

А о чем мне еще писать))  Хотя бы при порте твоего кода на шарп - могу обратиться с вопросами?)) 

MonkeyFirst  - предупреждать надо;) - я тут, что только не представил, переживал - а он в игрульки играет))

**Comment by Zamir7** [comment]
> но тогда флоу в движке не будет

А как ты его представляешь в движке? - если только в виде отдельного инструментария...

**Comment by 1vanK** [comment]
в виде отдельного инструмента только интерфейсная часть

**Comment by Zamir7** [comment]
У трупа встанет вопрос, как и у меня - зачееем он в движке?))

**Comment by 1vanK** [comment]
ок, твои предложения?

**Comment by Zamir7** [comment]
Никаких, просто спросил (заметь не о c#))

Просто вижу его как полезный инструмент, но логика движка имхо не подразумевает данную тематику

**Comment by 1vanK** [comment]
а где должна быть эта логика?

**Comment by Zamir7** [comment]
В виде отдельного приложения думаю, не знаю - потому и спрашиваю) Было бы здорово если труп его принял - просто сам для себя даже не могу обосновать его включения в движок

**Comment by MonkeyFirst** [comment]
>но логика движка имхо не подразумевает данную тематику

Да здрасте, логика ПлакатьДвиг5 и логика Уныла4 с самого начала что сразу подразумевала наличие такой штуки? Нет, конечно. Поэтому прикрутить можно даже на Уху я считаю.   

>даже не могу обосновать его включения в движок

а ты посмотри ситуации в которых эта фича юзается в других двигах, тут ничего нового не будет )

**Comment by Zamir7** [comment]
Я больше говорил о философии трупа... А так я только за!)) Скрестил пальцы уже)

**Comment by 1vanK** [comment]
> В виде отдельного приложения думаю, не знаю - потому и спрашиваю) 

хорошо, а если она в виде отдельного приложения, как ты будешь использовать это в игре?

**Comment by MonkeyFirst** [comment]
Когда порт создается, для него же задается кроме всего прочего и имя?
тогда:
В с++ может юзаться енумы
а в AS может юзаться что-то типа: 
```
for (int i=0; i < GetInputPortrNum(); i++)
{
String s = EmunInputPortName(i)
FlowPort = GetInputPortByName(s)
}
```

**Comment by Zamir7** [comment]
"как ты будешь использовать это в игре?" - я думал это наши головные боли)

**Comment by 1vanK** [comment]
> как ты будешь использовать это в игре?

в данный момент твоя, объяснить мне)

**Comment by Zamir7** [comment]
Сходу не отвечу, но костыли еще никто не отменял)  Ладно - сдаюсь)

**Comment by 1vanK** [comment]
> В с++ может юзаться енумы
> а в AS может юзаться что-то типа:

я вот думаю, мб тупо константы прямо в класс добавить?

**Comment by MonkeyFirst** [comment]
а мб ты прав сделай пока на mаp'у потом в процессе оптимизаци можно ее выпилить к черту)

**Comment by Zamir7** [comment]
Я свой, и первый с пеной у рта буду обосновывать трупу - как эта фича жизненно необходима для движка)

**Comment by Zamir7** [comment]
А почему у тебя нет output портов в сущ. контролах? Руки не дошли или не увидел необходимости у них

**Comment by 1vanK** [comment]
> а мб ты прав сделай пока на mаp'у потом в процессе оптимизаци можно ее выпилить к черту)

у меня уже прямо щас работает в AS без мапы
работающий пример залил с камераконтроллером
просто я хз как лучше константы с номерами портов организовать, чтобы они в глобальной области не маячили

**Comment by 1vanK** [comment]
> А почему у тебя нет output портов в сущ. контролах? Руки не дошли или не увидел необходимости у них

а где не хватает выходящих портов?

**Comment by Zamir7** [comment]
Извини что отвлек, все ок

**Comment by 1vanK** [comment]
если ты про биндинги то там почти ничег оне прокинуто в ангелскрипт кроме одной ноды

**Comment by Zamir7** [comment]
Я вот все не могу запустить проект у себя, может пути надо прописать или кинуть в определенную папку мне. Или он вовсе не рассчитан для запуска?)

**Comment by MonkeyFirst** [comment]
>Или он вовсе не рассчитан для запуска?)

Собери его СMake'ом, как любой другой проект ухи, и куда-то потом нужно копирнуть CustomEditor... в ResultsAnd...

**Comment by Zamir7** [comment]
CMake - брррр, я тут вспомнл - у меня и так фантазия неплохая -представлю как это все работает и все)

**Comment by 1vanK** [comment]
> у меня и так фантазия неплохая

я это заметил кстати)))))

**Comment by 1vanK** [comment]
короч кадавер написал, что в AS такой штуки нету, поэтому я тупо константы буду задавать в классе

**Comment by 1vanK** [comment]
как бы не так, константы внутри класса тоже хз как зарегистрировать в AS))

**Comment by Zamir7** [comment]
Переоткрывай заново ветку чтоль)

**Comment by 1vanK** [comment]
закрытость темы не мешает спамить)
