### ISSUE TITLE
About custom FlowNodes

### ISSUE THREAD

**Issue by MonkeyFirst** [1vanK/Urho3DFlowGraph#7]
В общем пока я сам достаточно расплывчато себе это представил, но вот что уже есть )

Есть такой компонент LogicComponent() в AS это видимо scriptObject?
Но опять же речь пока вообще не о AS и его биндингах)

Короче если добавить в LogicComponent статический метод который вызывается FGSystem при условии есть он был с особой маской, скажем вот такой метод:

```
OnFlowNodeUpdate(FlowNode* fn, LogicComponet* lg) 
{
//1. случай реакция на событие
if (Fn->InPortHasEvent["create"])
{
int typeObj = Fn->inport["typeofobject"]
// internal c++ logic for this node
lg->CreateUserStuff(typeObj);
}
//2 передача события дальше на выход
if (fn->InPortHasEvent["callPolice!"]) 
{
// port + value
fn->ActivatePort("callToPolice", "113");
}
}
```

А описываются эти порты могут вся так же в конструкторе у наследованного от LogicComponent'a - в юзер классe (UserLogic::LogicComponent... )

```
UserLogic::UserLogic(Context* context) : LogicComponent(context)
{
	SetUpdateEventMask(USE_FIXEDUPDATE);
	SetFlowGraphMask(USE_FLOWGRAPH);
}
```

В общем если FGSystem увидит у какого либо потомка от LogicComponent этот флаг USE_FLOWGRAPH
она тут же попытается опросить его на предмет описания портов входящих/ выходящих
какая-нибудь стандартная структура/вектор. 
Тут видимо опять нужно к LogicComponent'у добавить что-то вроде:

```
struct FGDesctiprion 
{
Vector<String> InputPortName;
Vector<Variant> InputPortDefaultValue;
Vector<String> OutputPortName;
Vector<Variant> OutputPortDefaultValue;
}

FGDesctiprion LogicComponent:: GetFlowGraphDescription() 
{
return fgDescription
}
```

FGSystem читает эти порты и создает у себя в спец. списке FlowNode для этого компонента. В процессе FlowGraph->Update() все евенты от такой FlowNode в графе адресуются этому компоненту через тот статический метод LogicComponent::OnFlowNodeUpdate();

В общем, пока вот, мб еще что позже допишу и исправлю.
Обсуждаемо... )

**Comment by 1vanK** [comment]
ААааа, я тупой, половину не понял)
Начни с того какую задачу это решает.

я пока обрывки информации попытаюсь прокомментировать
> LogicComponent 
LogicComponent подразумевает привязку к ноде, то есть к сцене, я хочу вообще независимую вещь сделать от сцены и прочего
На данный момент флоунода обычный объект, он также может подписыватся на события и отправлять события
Если должен с нодой какой-то работать, то передаешь эту ноду через порт

> FGSystem 
имеешь в виду подсистему? сейчас флоуграф это не подсистема, это просто объект который рулит флоунодами внутри него
Ты можешь 500 флоуграфов запилить. В том числе запихать кастомный флоуграф в какой-то LogicComponent и прилепть к ноде, чтобы флоуноды внутри этого флоуграфа всегда имели доступ к ноде без передачи через порт

**Comment by 1vanK** [comment]
Я короче знаешь что понял по поводу enumов? Что это бесполезная фигня. Когда ты пишешь код флоуноды на C++ ты пользуешься enum без проблем. Когда пользователь создает флоуграф из блоков в редакторе ему тоже абсолютно насрать, какие там енумы у портов. Он просто мышкой соединяет порты. Единсвтенное где нужны бинды enum в AngelScript - это если ты зачем то флоуноды создаешь вручную и вручную передаешь данные в порты. В этом случае без констант просто придется указывать номера портов.

**Comment by Zamir7** [comment]
Monkey, мало того что технически не понятно - ты  вдобавок еще и не на русском написал)

**Comment by 1vanK** [comment]
ну я не яснее излагаю порой))

**Comment by Zamir7** [comment]
Я тем более, но я про орфографию в данный момент)

Значит string все таки или константа?

**Comment by Zamir7** [comment]
> А описыватся эти порты могут вся так же
XD

**Comment by MonkeyFirst** [comment]
>Начни с того какую задачу это решает.
FlowNode'ы для встроенных стандатных флоунод это одно, а CustomFlowNodes это неколько другое. 
Поэтмоу приходиться для кастомных городить такую штуку.
Но благодаря как мне кажется тому что они создаются по некому стандартному описанию они легко должны прокидывать в редактор флоунод и в биндинги для as.

Короче как мне кажется, нужно писать рабочий пример кода иначе ничего не будет понятно )

**Comment by Zamir7** [comment]
Я бы попросил тебя прочитать наш вчерашний диалог с Иваном, может ты поймешь (оценишь) о чем я там?) Это как раз по теме

**Comment by Zamir7** [comment]
Там всего лишь три абзаца моих - но не поленись и перечитай его несколько раз, чтобы понять

**Comment by 1vanK** [comment]
MonkeyFirst ты после прочтения главное больше вопрос задавай, я понял что это работает))

**Comment by 1vanK** [comment]
MonkeyFirst кстати я наверно просто сделаю функцию GetPortIndex(string portName) которая будет перебирать порты, как ты советовал ранее. Все равно эта функция будет редко пользоваться и чисто в тестовых целях.

**Comment by Zamir7** [comment]
Не помню что были от тебя вопросы) Это тема отделения мух от котлет, не брезгуйте ей...

**Comment by 1vanK** [comment]
Я это седня понял,  надо было еще вчера задавать))

**Comment by Zamir7** [comment]
А главную мысль ты понял оттуда? Примерно?

**Comment by 1vanK** [comment]
понял, что у тебя есть крутая идея сделать все круто, а мы криворукие ))

**Comment by 1vanK** [comment]
больше к сожалению ничего не понял))

**Comment by Zamir7** [comment]
Про криворукость ты загнул канеш, а то что ты не понял - ничего страшного - перечитай еще раз и читай не спеша) Иногда помогает

**Comment by 1vanK** [comment]
отнюдь гордыня тут ни при чем)

**Comment by 1vanK** [comment]
я тебе такой вопрос задам, ты сам то понимаешь, что ты хочешь? ))

то есть идея сделайте ноду которая может все не годится вообще, покажи набросок, тыж программист, нарисуй хоть блоксхемку)

**Comment by Zamir7** [comment]
> ноду которая может все

Получилось нодЫ которые могут все. Суперфлоунода - на с++, как я окончательно убедился - не возможен. В виду отсутствия нормальной рефлексии. Я ее напишу на шарпе - когда время будет -т.е. никогда)) Ну или очень не скоро

**Comment by 1vanK** [comment]
хорошо, мы можем больше не возвращаться к этому? )

**Comment by Zamir7** [comment]
Про Суперфлоуноду я и слова не говорил, ни в той теме, ни сейчас. Я просто ответил на твой вопрос о нем. Что ты хочешь чтобы я не говорил?))

**Comment by 1vanK** [comment]
я хочу чтоб ты мне код показывал, который ты предлагаешь)

**Comment by Zamir7** [comment]
Код не нужен в том что я предлагаю) Я наоборот предлагаю без кода строить контролы - а на графе, как внутренние так и сторонние. А в процессе их разработки - автоматически образуется тот минимальный базис контролов - который способен (почти) на все. Неделимые кирпичики

**Comment by 1vanK** [comment]
а ну раз код не нужен, так рисуй кирпичики, в чем проблема) а я себе покожу пока)

**Comment by Zamir7** [comment]
Суть даже, больше не в том - писать контролы вручную или блоками, суть в нахождении тех самых базовых контролов - которые действительно необходимы для решения самых разнообразных задач

**Comment by Zamir7** [comment]
Делай че кайф) Все равно так и поступишь))

**Comment by 1vanK** [comment]
так а идея то в чём состоит твоя?

**Comment by Zamir7** [comment]
Я хотел мнение MonkeyFirst узнать - а он слинял куда то) Игры конечно интереснее)

**Comment by 1vanK** [comment]
у меня желание слинять вторые сутки уже)) но ты обидешься, если я перестану отвечать)

**Comment by Zamir7** [comment]
Вот это самопожертвование - вау) Я торжественно обещаю не обижаться - так сойдет)

**Comment by 1vanK** [comment]
ну вчера ты обиделся ) типа "я умываю руки, черт с вами, неумехи" ))

**Comment by Zamir7** [comment]
Да нее, подумал, если я просто не нужен здесь и не приношу пользу  - нахера мне мешаться под ногами и отвлекать попусту)

**Comment by 1vanK** [comment]
аа ну сори)

**Comment by 1vanK** [comment]
уф, раз 10 уже переделал классы, чтоб вы понимали, как все продумано будет)

**Comment by MonkeyFirst** [comment]
))
Вот что-то типа этого я имел ввиду когда писал выше про кастомную ноду. 

https://github.com/MonkeyFirst/Urho3DFlowGraph/blob/customFlowNodeComponent/CustomFlowNodeComponent/CustomFlowNodeLamp.cpp

В примере она просто управляет лампочкой. 
И если смотреть на этот граф с позиции редактора графов, то тут используется две стандартных флоуноды и одна кастомная прокинутая в граф, хотя это на самом деле компонент навешиваемый на Node. Флоуграф для нее создается по описанию, которое как я думаю можно про кинуть на сериализацию, а дальше в редактор графов. В этом случае нет необходимости как-то регистрировать новые ноды в редакторе а только лишь в проекте как и обычный компонент.

**Comment by 1vanK** [comment]
Так это я еще только предполагаю, что МОЖЕТ понадобиться и с учетом этого переделываю. И я что-то сомневаюсь что учел все)

**Comment by MonkeyFirst** [comment]
>И я что-то сомневаюсь что учел все)
Подсчет визитов по портам у нод можно использовать в качестве дебаг инфы по частоте использования нод в графе. Скажем, если порты у ноды обновляются с частотой FGSys->Update(timeStep) т.е. каждый кадр, то помечать её в редакторе (при включенном дебаге) красным цветом или порт с большой частой красить.

Так же по идее нужно добавить частоту обновления графа и его нод. Т.к. для какого-то графа/ноды и 1 раз в секунду очень быстро.
Кстати некоторые параметры самого графа нужно сделать доступными для чтения и изменения самими нодами. Так скажем кастомная нода, может прокинуть в граф событие из Node'-ивентов как раз для изменения частоты выполнения FlowGraph в котором она состоит, в случае если объект стал не видимым и нет необходимости обновлять граф часто.

Активация деактивация графа целиком.

...

**Comment by 1vanK** [comment]
нет у меня никаких визитов по портам...

**Comment by 1vanK** [comment]
да и не может быть иначе, вот взять как пример камера контроллер, у него входные данные не меняются, а выходных данные вообще нет, но он меж тем управляет камерой каждый кадр

**Comment by Zamir7** [comment]
люди, а почему вы на разных репо мутите? Вы соревнуетесь чтоль?

**Comment by MonkeyFirst** [comment]
ok, если не визиты то частоту вызова апдейта то можно добавить ?

FlowGrapth->SetUpdateFrequency(60); //Обновление 60 раз в секунду
FlowNode->SetUpdateFrequency(0) //Обновление с каждым апдейтом

Ты FG-систему собираешься добавлять, для менеджмента графами и исполнения кастомных нод ?


>люди, а почему вы на разных репо мутите? Вы соревнуетесь чтоль?
Ядро системы еще не стабилизоровалось, я думаю оно еще не раз перепишется )
И потом я просто смотрю на процесс и демонстрирую свой вариант того-то или иного компонента, не буду же я это пуллить в основной репо.

**Comment by 1vanK** [comment]
> FlowGraph->SetUpdateFrequency(60); 

а такое вообще где-то есть? Добавить функцию не проблема если что

> Ты FG-систему собираешься добавлять

А какие функции она должна выполнять? Я имею в виду конкртеные действия, чтобы лучше понимать что ты имеешь в виду?

а чем кастомные ноды отличаются от некастомных?

**Comment by 1vanK** [comment]
Вообще щас флоуграф отдельный объект, который можно воткнуть куда угодно и котоырх может пыть хоть 100 шутк. Ты можешь от него наследоваться и назвать например FlowGraphForScene. А поместить в Component для сцены.

**Comment by 1vanK** [comment]
> люди, а почему вы на разных репо мутите? Вы соревнуетесь чтоль?

а почему нет, вдруг у кого-то лучше получится)

**Comment by 1vanK** [comment]
Залил коммит, теперь версия на скриптах и запущенная через кастомный плеер полностью повторяет работу старой C++ версии. В процессе заливки коммита пришла идея запилить шаблонную функцию, как любую новую кастомную флоуноду зарегистрировать для AS одной строчкой)

**Comment by MonkeyFirst** [comment]
>а такое вообще где-то есть?

Конечно, вообще они не исполняют какую-то привязанную к ним логику по Update() каждый кадр.  Только лишь помеченная специальным флагом флоунода апдейтится с каждым кадром. У края это флаг SetRegularUpdate (true) для ноды. Хз что там у уныла4...

>А какие функции она должна выполнять? Я имею в виду конкртеные действия, чтобы лучше понимать что ты имеешь в виду?

Для начала можно это https://github.com/MonkeyFirst/Urho3DFlowGraph/blob/customFlowNodeComponent/CustomFlowNodeComponent/FlowGraphSystem.h

потом можно добавить походу пьесы:
- сериализация графов в файлы / загрузка графов из этих файлов
- удаление графов (система контейнер для графов)
...

>И чем кастомные ноды отличаются от некастомных?

не кастомные - "забитые гвоздями" в движке флоуноды, которые не подлежат изменениям, лишь только юзаются в графах, перетаскиваются из toolbar'a.

кастомная нода - Component для Node который представлен в графе портами кототый определил пользователь в описании своего Component, действия обрабатыватюся так же внутри такого Component'а.

Ты хоть смотрел ту лампочу что я выше приводил в пример кастомной ноды? 
Мб там это несколько косячно выглядит пока, но кастомная нода всегда определяется уже в конечном проекте, а движку чтобы её правильно представить в графе или исполнить - нужны какие-то стандартные "костыли".

Я просто примерно знаю как это в крае5 выглядит и работает. Возможно нужно подождать что ты дальше придумаешь: Что такое кастомная нода у тебя? И как я смогу обрабатывать и отсылать сообщения из Component'ов Node в граф,

**Comment by 1vanK** [comment]
> Ты хоть смотрел ту лампочу что я выше приводил в пример кастомной ноды?
пока не до лапочки было, щас посмотрю

**Comment by 1vanK** [comment]
а ты мог бы сохранять файлы в UTF-8? а то вместо кириллицы кракозябры(

**Comment by 1vanK** [comment]
блин, где лампочка, ткни меня мордой( я таймер только нашел

**Comment by 1vanK** [comment]
а, нашел, а я в репозитории искал)

**Comment by 1vanK** [comment]
А что должен мне показать пример с лампочкой? Я 15 раз примерно написал, что объект флоуграф можно запихнуть куда угодно (в тот же компонент для ноды) и использовать для манипуляции с нодами и др объекатми в сцене

> Мб там это несколько косячно выглядит пока, но кастомная нода всегда определяется уже в конечном проекте, а движку чтобы её правильно представить в графе или исполнить - нужны какие-то стандартные "костыли".

у меня тоже так, на данный момент я просто прокинул 3 кастомные ноды в урхоплеер чтобы проверить биндинги и понять как потом сделать это для стандартных нод, которые будут в движке.
А также для редактора был прокинут БАЗОВЫЙ класс flownode, который и будет использовать при редактировании, соединении портов линиями и так далее.

Интерфейсная часть, будут полностью реализована на ангелскрипт для редактирования в эдиторе. И ей плевать какой там код внутри флоунод. Ей только будут нужны данные о портах из xml-файлика. И опять повторюсь же, что текущая работа вообще этому никак не мешает и не противоречит.

**Comment by 1vanK** [comment]
> Конечно, вообще они не исполняют какую-то привязанную к ним логику по Update() каждый кадр. Только лишь помеченная специальным флагом флоунода апдейтится с каждым кадром. У края это флаг SetRegularUpdate (true) для ноды. Хз что там у уныла4...

чем хранить массивы мутных конструкций, массивов и флагов не проще ли самой ноде дать возможность решать нужен ли ей апдейт? например так
```
МояНодаКОтораяОфигетьКакГрузитПРоцессор::Update(float timeStep)
{
    if (апдейт не требуется)
       return;
    //А тут код который ставит на колени любой компьютер
}
```

**Comment by MonkeyFirst** [comment]
>Я 15 раз примерно написал, что объект флоуграф можно запихнуть куда угодно

Я наверное столько же раз пишу, что мне не нужна флоунода сама по себе (запихнутая куда либо).
У меня есть Component с какой-то игровой логикой (персонаж скажем) и я хочу вывести его в граф. Мне удобнее с Component и привычнее. О системе флоунод я вообще в этом случае ничего не буду знать, да мне и ненужно особо (как пользователю) кроме того как "потаскать и посоединять" их как-то в визуальном редакторе графов, и там будет мой Component(Персонаж) для Node с нужными мне портами. И обработка будет в нутри этого Component.

**Comment by 1vanK** [comment]
Ну так вот смотри, ты создаешь компонент с флоуграфом внутри. Настраиваешь его как надо. А потом бац и наследуешь от этого компонента 100500 своих компонентов?

**Comment by 1vanK** [comment]
ПОд настройкой я подразумеваю связь между компонентом и флоуграфом в нем.

**Comment by 1vanK** [comment]
Короч пока на практике все надобности не будут исследованы, то все еще будет переписано не раз. Я просто не понимаю о тех фичах, которые ты мне показываешь, почему они не могут быть сделаны прямо щас

**Comment by 1vanK** [comment]
В общем то что щас есть. Тебе нужен флоуграф с примочками? Наследуй от базового флоуграфа. Теебе нужна касмомная фоунода? Наследуй от базовой флауноды.
Именно базовый классы прокидывается в редактор и используется для редактирования. И именно на базовых классах я сейчас сосредотачиваюсь.

**Comment by MonkeyFirst** [comment]
>МояНодаКОтораяОфигетьКакГрузитПРоцессор 
)))
ну может быть и так ) 

>Ну так вот смотри, ты создаешь компонент с флоуграфом внутри

Ну)

>Настраиваешь его как надо.

Нет) Описываю порты уже в конечных потомках и все. (аналогия с LogicComponent ты в потомках что-то оформляешь для логики, так и тут порты и логика обработки в потомках от CustomFlowNode)
А настройка графа, связей, загрузка из файла должна идти в общем месте для всех графов т.к. Component имеет ссылку на ту же обычную flownode в FGSystem.    

>Короч пока на практике все надобности не будут исследованы, то все еще будет переписано не раз.

Да вот же)

**Comment by 1vanK** [comment]
> Нет) Описываю порты уже в конечных потомках и все. (аналогия с LogicComponent ты в потомках что-то оформляешь для логики, так и тут порты и логика обработки в потомках от CustomFlowNode)
А настройка графа, связей, загрузка из файла должна идти в общем месте для всех графов т.к. Component имеет ссылку на ту же обычную flownode в FGSystem.

да ты пойми, что специфические флоуграфы и флоуноды для конкретных целей это дело десятое, нужен базовый интерфейс, которй будет в редакторе
вот про тот пример который ты говоришь я б наследовал от базового флоуграфа новый и сделал бы в нем глобальную переменную с указателем на ноду и автоматически подавал бы указатель на порты нод внутри него, либо твои кастомные ноды могут получать этот указатель из графа, а может ты хочешь события доавить? да ради бгога добавь события, ведь это обычные объекты урхо. Но в базовом классе этого нифига не  нужно.

**Comment by 1vanK** [comment]
Я бы лучше от тебя примеров заковыристых хотел, как ты обычно ноды используешь, по типу; прилепляю туда-то, состоят из такой такой то и такой то ноды, они делают в итогде то-то
Мне кажется так бы мы лучше понимали друг друга, и я бы как раз понимал можно ли это сделать щас или нужно переделывать

**Comment by MonkeyFirst** [comment]
>Я бы лучше от тебя примеров заковыристых хотел
>они делают в итогде то-то

Ok.
Сцена "сайфайная дверь(или лифт) и персонаж"
Перед дверью расположен большой триггер (куб)
Если персонаж заходит в триггер (под управлением юзера) - контроль перса юзером прерывается, задействуется cinеmatic-камера, включается анимация где перс подходит к панели управления двери и нажимает пару кнопок после чего - дверь открывается. Перс вновь переходит под управление игрока. 

Если сильно круто ?

Тогда попроще: есть пушка охраны она в выключенном состоянии по умолчанию. Но если в радиус действия её радаров попадется игрок то она: сначала активизируется, а затем начнёт стрелять по игроку, ну и поистечению некоторого времени, если игрок скрылся из поля ее зрения она вновь уходит в "спящий режим".

**Comment by 1vanK** [comment]
а в разбивке на флоуноды?

**Comment by MonkeyFirst** [comment]
Ты же их создатель, я не могу знать какие не увидев их
Но в крае я думаю это был бы Flowgraph навешанный на этот триггер в сцене
в графе был бы - ProximityTrigger с выходом EnterArea + кастомная нода для перса с моими портами.
может быть, еще более длинный вариант с доп. flownode Animation которая бы добавляла персу в очередь более приоритетную анимацию с открыванием двери, и пока она isPlaying контроля бы не давал игроку. А CurrentCamera жила бы тоже тут же, но по заранее сохраненному анимационному треку

**Comment by 1vanK** [comment]
> Но в крае я думаю это был бы Flowgraph навешанный на этот триггер в сцене

я вот это и хочу знать, как бы ты сделал в крае

**Comment by 1vanK** [comment]
и вот эти все флоуноды, которе всем этим управляют в одном флоуграфе для сцен находятся? или флоуграф это вообще глобальная на весь игру штуку?

**Comment by MonkeyFirst** [comment]
ну иерархия такая же как и у тебя: Flowgraph а в нутри flownod'ы
только Flowgraph вешается на Entity т.е. на Node. т.е. это Component а не что-то параллельно живущее.    http://savepic.net/8739260.htm

**Comment by 1vanK** [comment]
а несколько флоуграф, развешанных на разные объекты шлют широковещаетльные кастомные события я так понимаю?

**Comment by 1vanK** [comment]
ну чтоб взаимодействовать

**Comment by MonkeyFirst** [comment]
я не настолько их курил еще, мне хватало локальной логики работы графа.

вот еще. благодаря той ерунде что я выделил на рисунке
http://savepic.net/8723900.htm
граф может реюзатся для кучи подобных обьектов в сцене (однажды его описав в редакторе, можно юзать на разных инстансах одинаковых объектов), потомучто типо точкой входа/ресурсом является текущая entity = Node

**Comment by MonkeyFirst** [comment]
ты лучше установи край и проиграйся с ними я мало их вообще курил, и весь мой интерес был в том чтобы представить своих персонажей или какие-либо интерактивные объекты в графе

**Comment by 1vanK** [comment]
у меня даже твоя демка крашилась на запуске помнишь? )

**Comment by MonkeyFirst** [comment]
скачай ламбар тогда там теже графы )

**Comment by 1vanK** [comment]
> ламбар 

каво?

**Comment by MonkeyFirst** [comment]
https://aws.amazon.com/ru/lumberyard/

**Comment by 1vanK** [comment]
так это тот же край

**Comment by 1vanK** [comment]
я луче у тебя поспрашиваю, как уже более менее разбирающегося, чем с нуля изучать новый для меня движок, такими темпами реализация флоуграфа отдалится на годы))

**Comment by MonkeyFirst** [comment]
версия края там постарее  мб пойдет, к тому же если ты помнишь я писал что у людей и на GT420 идет край только дико тормозит, так что это видимо у тебя траблы с дроваим или еще чем-то

**Comment by 1vanK** [comment]
В общем благодаря тебе я понял, что еще в самой флауноде нужно хранит указатель на флауграф, в котором она находится. Тогда в графе можно всякие глобавльне штуки хранить, а нода сможет обращаться к ним flownode->GetGraph()->GetVar(...)

пока что я буду реализовывать интерфейсную часть, чтобы легче было обкатывать и если что поменять все вместе уже

**Comment by 1vanK** [comment]
а такой вопрос, ты в крайэнжине писал уже свои собственные флауноды?

**Comment by MonkeyFirst** [comment]
Конечно, два типа делал:
Первый тип не требующий привязки к Entity (типа простых математических или любых других служебных)
типа как сейчас у тебя флауноды ничего им не нужно от Scene для работы

И другой тип флоунод который привязывается к Entity, или даже проще является представлением Entity в FlowGraph'e.

**Comment by 1vanK** [comment]
Хорошо, вот ты написал свой класс (на си++ я полоагаю), дальше что происходит? Как ты его компилируешь? В движок или игру? Я имею в виду редактор тамошний часть игры или отлельное приложение? И есть ли возможность в редакторе запускать на исполнение сцены, в которых есть твои кастомные ноды? Как это организовано?

**Comment by 1vanK** [comment]
А может там твой код компилируется в какую-то dll-ку, которая подгружается и в редактор и в игру? Работает ли подключение новой ноды без перезапуска редактора?

**Comment by MonkeyFirst** [comment]
>Я имею в виду редактор тамошний часть игры или отдельное приложение?

Отдельное

> И есть ли возможность в редакторе запускать на исполнение сцены, в которых есть твои кастомные ноды (ты нажал кнопку Run и бах твоя нода работает как встроенные)?

Конечно, можно даже только что собранный проект из студии в Sandbox'e запускать (редактор)

>А может там твой код компилируется в какую-то dll-ку, которая подгружается и в редактор и в игру? 

Да, проект это всегда dll'ка которую исполняет GameLancher или Sandbox

>Работает ли подключение новой ноды без перезапуска редактора?

Нет, я не могу собрать проект в студии, если он у меня открыт в Sandbox-редакторе ))

**Comment by 1vanK** [comment]
а есть ли какие-то идеи, как сделать подобную подгрузку dll ок для урхо? ведь реально убого выглядит, ты редактируешь дерево нод, но даже не имеешь возможности запустить на исполнение

**Comment by 1vanK** [comment]
хотя и щас можно движко в дллку запилить ведь, правда это будет модфицированный движок с твоей нодой, хм

**Comment by 1vanK** [comment]
а хотелось бы движок скомпилировать и не трогать его, а свои классы отдельно в твоей дллке держать и чтоб ее можно было в редакторе использовать и в игре

**Comment by MonkeyFirst** [comment]
Можно по идее вынести описание своих нод в сторонний файл который юзает редактор флоунод
Это может делать FG-подсистема когда поймала все кастомные ноды, и при запуске просто записала все их описания в bin/Data/Flownodes/CustomFlowNodes.xml. В это файл писать имя класса кастомной ноды(чтобы знать что потом инстансить в флоу редакторе на AS ) и инфу о портах. Как-то так наверное.

**Comment by MonkeyFirst** [comment]
Ты посмотри еще раз на мою кастомную ноду для лампочки, посмотри как ей мало надо для того чтобы появится в редакторе графов. Как я писал выше инфа о портах + имя класса.

**Comment by 1vanK** [comment]
Я прикинул что в AS тут вообще не надо ничего экспортировать, если это даже  не будет возможным запустить. Редактор тупо парсит xml файлики, выдергивает оттуда список портов и позволяет возюкать квадратики по экрану. Все. Ему даже знать не надо о всяких флоусистемах. НО без возможности отладить граф это как-то не очень.

**Comment by MonkeyFirst** [comment]
да хотябы так)

**Comment by 1vanK** [comment]
тогда я щас могу сделать сериализацию (сохранение) графа нод в xml и на этом работа с движком заканчивается. И начинается другая, абсолютно отдельная и никак не связанная работа с возюканьем квадратиков по экрану.

**Comment by MonkeyFirst** [comment]
это какая?)

**Comment by 1vanK** [comment]
там запятой не хватает, щас исправлю))

**Comment by 1vanK** [comment]
типа начинается работа с возюканьем))

**Comment by 1vanK** [comment]
таким образом нам надо будет хранит в папке с редактором набор xml описывабщих порты у всех флоунод (в том числе и встроенных в движок)

**Comment by 1vanK** [comment]
и юзер туда добавляет свои хмлки, как то так это будет выглядеть

**Comment by MonkeyFirst** [comment]
пока так, а там может что еще какая светлая мысль посетит

**Comment by 1vanK** [comment]
ну я написал там https://github.com/urho3d/Urho3D/issues/1724 фича реквест, это бы все рашило и не пришлось бы xmlками мусорить в папке с редактором

**Comment by MonkeyFirst** [comment]
Ты же примерно знаешь что тебе ответят ?) пулл-реквест ар а вильком ))
Ты дополни что было бы не плохо хотябы увидеть пример регистрации новых component'оз из некоторой dll'ки

**Comment by 1vanK** [comment]
как минимум обсуждение начать, может он сразу пошлет)

**Comment by 1vanK** [comment]
Кстати вот регистрация компонентов в данном случае и не требуется)

**Comment by 1vanK** [comment]
Конечно если ты пилишь флоуноду как часть компонента, то потребуется конечно, но в общем случае просто нужно создавать объекты определенного типа

**Comment by MonkeyFirst** [comment]
Короче чтобы context был доступен в DLL'ках
А там можно делать с ним что хочешь.

**Comment by 1vanK** [comment]
плагины я точно рганизовать не смогу, cadaver говорит что реалэкстенд (его втором движке есть плагины), но это нифига некросплатформенно

**Comment by 1vanK** [comment]
вот как функции дергать из DLLки я знаю, а вот как типы??

чтобы тип получить из dll ки надо ведь .lib файл прилинковать к приложению, а значит само приложение перекомпилровать, ну и плюс чтобы в исходнике эти новые типы из dll ки использовать нужен еще *.h файл с описанием этих типов

я чет уверен, что в крайэнжине sandbox не перекомпилируется при создании каждой новой флоуноды

**Comment by MonkeyFirst** [comment]
>я чет уверен, что в крайэнжине sandbox не перекомпилируется при создании каждой новой флоуноды

нет, конечно ) в проекте юзверь пишет только "кастомности" все стандартное сидит в движке.

>вот как функции дергать из DLLки я знаю, а вот как типы??

а зачем? ты же уже можешь получить в движек базовый класс FlowNode от любой SuperPuperCustomFlowNode и можешь узнать о ней все что нужно по портам. 
Можно еще что-то вроде FlowNode::GetInfo() добавить и в потомках фидить инфой структуру для этого метода, движек или редактор флоунод будет работать только с FlowNode и этим методом для конструирования флоунод, это если портов мало, для того чтобы узнать о ноде что-либо.

**Comment by MonkeyFirst** [comment]
да редактор не сможет инстансить кастомности из проекта юзера, но вроде ты и так решил отказаться от этого, тогда зачем dll'ки ?

**Comment by 1vanK** [comment]
так я хотел бы чтоб в редакторе можно было нажать run и все работало как в крайэнжине)

**Comment by 1vanK** [comment]
пока изучаю как в тундре плагины сделаны (тут модулями называютс) а там гляну чо как делать дальше

**Comment by 1vanK** [comment]
если честно у меня щас большое желание забить на anglescript (ну из этого следует что и на пулреквест в официальный репо), так как мне уже и так приходится перекраивать флоуграф, чтобы удовлетворить капризы англескрипта, а ведь потом еще для LUA корячиться

**Comment by MonkeyFirst** [comment]
>а ведь потом еще для LUA корячиться

а потом еще скажут "акшели ам нот хаппи вив ит, ваи ю джаст гет алл вис анд..." )

**Comment by 1vanK** [comment]
плагинная система в тунре не выглядит сложной, даже инетересно поэкспериментировать, узнать в каких пределах удастся развернуться

**Comment by 1vanK** [comment]
можно даже попробовать запилить плагинную систему в виде поджсистемы урхо. То есть добавил файлик с подсистемой в свой любой проект и оп-ля он умеет загружать плагины. Хоть в плеер добавь кастомный, хоть в свою игру

**Comment by 1vanK** [comment]
Короч добавил пример сериализациии нод прямо в кастомный урхоплеер, запускаешь плеер с любым скриптом или вообще без, он создает флоуноду CustomCamera и сохраняет ее в файл. Таким макаром можно любую кастомную ноду сохранить, чтобы потом в редакторе парсить этот файлик и знать какие у нее порты

**Comment by 1vanK** [comment]
Формат файлика проще некуда 
https://github.com/1vanK/Urho3DFlowGraph/blob/master/ResultAndSample/CustomEditorData/FlowNodes/CameraController.xml

**Comment by MonkeyFirst** [comment]
Круто, я вижу у тебя уже окно есть flow graph editor.
Когда первые кирпичи будут ?) Кстати, как ты эту линию собираешься рисовать, которая соединяет порты ?

**Comment by 1vanK** [comment]
придумаю, когда дойдет дело

**Comment by 1vanK** [comment]
да вообще легко в событии ENDRENDER или как там его, функциями подобными debugRender воспользоваться для рисованя лииний

**Comment by 1vanK** [comment]
конечно это костыльнй метод, но пока что тут костыль на костыле и костылем подпирает)

**Comment by MonkeyFirst** [comment]
Я вот пока собирал UIFlowNode из других UIElement'ов, думал а как эта штука будет сообщать о своих каких то кастомных событиях ?
типа - UI_FLONODE_PORT_CONNECTED/DISCONNECTED

**Comment by 1vanK** [comment]
а ты собрался перестраивать флоуграф в процессе игры?

**Comment by MonkeyFirst** [comment]
нет) это для редактора флоуграфов, по идее удобнее же, нет?

**Comment by 1vanK** [comment]
зачем какие-то события, если нет возможности даже запустить это)

**Comment by 1vanK** [comment]
рассматривай это как рисование квадратиков в пейнте)

**Comment by MonkeyFirst** [comment]
Ну так в пеинте есть кисточка и при нажатии кнопки она шлет какое то сообщение другой своей части чтобы та рисовала что-то. Я же про редактор говорю, а не про запуск графа в игре или его редактирование на ходу.

**Comment by 1vanK** [comment]
рисование линий каждый кадр (как и дебаг рендер), там предварительно батчи не создаются
```
forech (соединение)
{
   DrawLine(координатыПорта1, координаты порта2);
}
```

**Comment by MonkeyFirst** [comment]
дешево и сердито ))

**Comment by 1vanK** [comment]
Короч текстурки флоуноды и портов вынес в отдельные файлы, пока это просто квадратики, но можно сделать красивые закругленные элементы, полупрозрачные и какие угодно. Но украшательство всякое это на потом )

**Comment by MonkeyFirst** [comment]
Дизайн нод Блендера как ориентир?
Кстати, ты уже пробовал восстанавливать рабочий граф из файла, даже в ручную прописанный в файл. Там наверное какие-то индексы в пределах графа нужно присваивать нодам (к примеру индексировать по очереди добавления в граф во время его создания в редакторе графов), чтобы знать потом какая линия к какому ноду присоединена.

**Comment by 1vanK** [comment]
> Кстати, ты уже пробовал восстанавливать рабочий граф из файла, даже в ручную прописанный в файл.

не дошли еще руки, но там ничего сложно не видно, при редактировании все будет на указателях, а при сохранении в файл/загрузке через индексацию будет, да

**Comment by 1vanK** [comment]
давай новую иссую откроем, а то это полотно листать уже напряжно )

**Comment by MonkeyFirst** [comment]
давай ) new issue/trouble: galaxy on fire )

**Comment by 1vanK** [comment]
Сорри что по мелочи добавляю, учеба заставляет ) буду по вечерам понемногу кодить)

**Comment by MonkeyFirst** [comment]
Тебя никто не гонит код писать, если только ты сам. Так что когда угодно будет пиши )

**Comment by 1vanK** [comment]
Просто я чувствую большую ответсвтенность, если не я то кто? )))

**Comment by MonkeyFirst** [comment]
Ты прав, больше не кому( 
Ты последний в строю, впереди - враги, позади - %capital city%. 
А отступать и сдаваться никак низяя ))
